name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare-yarn-cache:
    name: Prepare Yarn Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install

  lint:
    name: Lint
    needs: prepare-yarn-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn lint:eslint
      - run: yarn lint:prettier --no-write --check

  test-node:
    name: Test on Node.js v${{ matrix.node-version }}
    needs: prepare-yarn-cache
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
      - run: yarn test

  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    needs: prepare-yarn-cache
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn test

  test-coverage:
    name: Test on Ubuntu with coverage using Node.js LTS
    runs-on: ubuntu-latest
    needs: prepare-yarn-cache

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v3
        with:
          directory: "./coverage"
