name: publish-to-npm
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: lts/*
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn config set npmPublishAccess public
      - run: yarn npm publish
