name: publish-to-npm
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: lts/*
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn config set npmPublishAccess public
      - run: yarn npm publish
