name: publish-to-npm
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: lts/*
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn config set npmPublishAccess public
      - run: yarn npm publish
